GameItem and AI info viewable in new debug UI
JohnoRobson/GodotBattleRoyal pull request #50
Opened 2024-12-27 18:06 UTC by JohnoRobson

This adds a debug UI that can be toggled on and off by pressing "Ctrl+B" during gameplay that shows the stats of weapons and actors, and by clicking on an AI actor, their latest evaluations are shown as well.

The GameItem and actor information is gathered by the new Reporter node, it takes a list of variable names that it will check its parent node for and returns a dictionary of key/value pairs of those variable names and their values. It also contains logic for converting certain node values into strings so that they can be red clearly. Reporters have been added to the different GameItem and Actor scenes. The ReporterViewer node checks all top-level nodes for the presence of Reporters, and gathers their information so that it can display them.

StateEvaluationMemory has been added to the StateMachines, so that they now hold the last 5 sets of evaluations that they have made. This is not used currently, but could be used as memory for projecting what future evaluations could be, and acting upon those predictions.

2025-01-11 05:11 UTC, morganwynne requested changes
Please address the script in the scene directory.

2025-01-11 18:16 UTC, JohnoRobson commented on scenes/components/reporter/reporter_container.tscn
> +text = "test:test"
Removed

2025-01-11 18:16 UTC, JohnoRobson commented on scenes/debug_ui.gd
That was a mistake, I've moved debug_ui.gd into the scripts directory

2025-01-11 18:17 UTC, JohnoRobson commented on scenes/scene.tscn
> +text = "AI: etc
removed

2025-01-11 18:18 UTC, JohnoRobson commented on scripts/ai/decision_maker.gd
> +	return get_states_to_do(controller)[0].state
I've replaced it with a check and assert, and it will log an error before returning a base `State` if the array is empty because I prefer that over returning a null

2025-01-11 18:18 UTC, JohnoRobson commented on scripts/ai/state_machine.gd
> +	previous_state_evaluations = StateEvaluationMemory.new(5)
Fixed!

2025-01-15 05:01 UTC, morganwynne approved these changes

2025-01-15 05:01 UTC, merged